name: Publish

on:
  workflow_dispatch:

env:
  TURTLE_VERSION: 0.23.1
  EXPO_CLI_VERSION: 4.12.10
  EXPO_SDK_VERSION: 43.0.0
  EXPO_USERNAME: xenfo
  EXPO_PASSWORD: ${{ secrets.EXPO_PASSWORD }}
  EXPO_IOS_DIST_P12_PASSWORD: ${{ secrets.EXPO_IOS_DIST_P12_PASSWORD }}
  EXPO_ANDROID_KEYSTORE_PASSWORD: ${{ secrets.EXPO_ANDROID_KEYSTORE_PASSWORD }}
  EXPO_ANDROID_KEY_PASSWORD: ${{ secrets.EXPO_ANDROID_KEY_PASSWORD }}

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.6.2]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Expo CLI
        uses: expo/expo-github-action@v6
        with:
          expo-cache: true
          token: ${{ secrets.EXPO_TOKEN }}
          expo-version: ${{ env.EXPO_CLI_VERSION }}

      - name: Get Yarn Cache Directory
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore Yarn Cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        run: yarn -s --frozen-lockfile --prefer-offline

      - name: Publish App
        run: yarn lerna exec --scope @utils/app expo publish

  build_android:
    name: Build Android
    runs-on: ubuntu-latest
    needs: [publish]

    strategy:
      matrix:
        node-version: [16.6.2]
        java-version: [8]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Decrypt Keystore
        run: gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.DECRYPT_PASSWORD }}" --output ./.github/secrets/utils.jks ./.github/secrets/utils.jks.gpg

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up Java ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: ${{ matrix.java-version }}

      - name: Install Expo CLI
        uses: expo/expo-github-action@v6
        with:
          expo-cache: true
          token: ${{ secrets.EXPO_TOKEN }}
          expo-version: ${{ env.EXPO_CLI_VERSION }}

      - name: Get Yarn Cache Directory
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore Yarn Cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Restore Turtle Cache
        uses: actions/cache@v2
        id: turtle-cache
        with:
          path: ~/.turtle
          key: turtle-${{ runner.os }}-${{ env.EXPO_SDK_VERSION }}-android

      - name: Install Dependencies
        run: |
          yarn global add turtle-cli
          yarn -s --frozen-lockfile --prefer-offline

      - name: Setup Turtle
        run: turtle setup:android --sdk-version ${{ env.EXPO_SDK_VERSION }}

      - name: Build App
        run: |
          cd packages/app
          turtle build:android -t apk -o ~/utils.apk --keystore-path ../../.github/secrets/utils.jks --keystore-alias ${{ secrets.EXPO_ANDROID_KEYSTORE_ALIAS }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Upload APK
        run: aws s3 sync ~/utils.apk s3://xenfo-utils/android/${{ env.EXPO_SDK_VERSION }}/utils-${{ hashFiles('../utils.apk') }}-signed.apk --acl public-read

      - name: Update README.md
        run: node .github/scripts/updateReadme.js "https://xenfo-utils.s3.us-east-1.amazonaws.com/android/${{ env.EXPO_SDK_VERSION }}/utils-${{ hashFiles('../utils.apk') }}-signed.apk"
